# Generated by Django 5.1.1 on 2024-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('visitas', models.PositiveBigIntegerField(default=1)),
                ('ultima_visita', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
