# Generated by Django 5.1.1 on 2024-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='região',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
